### PR TITLE
update to go1.16

### PR DESCRIPTION
**Pull request by boddumanohar**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
this PR updates the go version to 1.16

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
/ok-to-test
why need go 1.16?

**Comment by boddumanohar** [comment]
TBH, no particular use case for this project 😅 . I actually updated my go version to 1.16 today while working on [this k8s task](https://github.com/kubernetes/kubernetes/issues/96169#issuecomment-756335260) and after that when I run `make verify` on this project that commands is failing because it produced the above diff. So creating a PR.

**Comment by andyzhangx** [comment]
fixed by https://github.com/kubernetes-sigs/blob-csi-driver/pull/359

**Pull request closed without merging**
