### PR TITLE
fix: install blobfuse binary for Azure Stack test pipeline

### PR DESCRIPTION
**Pull request by songjiaxun**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:
Install the latest blobfuse binary for the Azure Stack test pipeline.

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by songjiaxun** [comment]
@andyzhangx  can you help retest the failed sanity test? The failure is not related to the change I believe.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
