### PR TITLE
WIP Improved Unit-Test Coverage for Issue #703 (please see #736)

### PR DESCRIPTION
**Pull request by aarongalang**
**What type of PR is this?**
test

**What this PR does / why we need it**: 
Adds unit-tests to pkg folder for improved coverage

**Which issue(s) this PR fixes**: 
#703 

Fixes #

**Requirements**:
  
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
thanks, could you:
 - sign off the cla 
 - fix the test failure

Thanks.

**Comment by aarongalang** [comment]
> 

Test Failure should be fixed now with the faulty test case removed in nodeserver test. CLA is signed, but I'm not sure why that particular commit isn't using my user id

**Comment by andyzhangx** [comment]
@aarongalang could you fix the golint error? Thanks.
```
run golangci-lint
  Running [/home/runner/golangci-lint-1.45.2-linux-amd64/golangci-lint run --out-format=github-actions -E=gofmt,deadcode,unused,varcheck,ineffassign,revive,misspell,exportloopref,asciicheck,bodyclose,depguard,dogsled,dupl,durationcheck,errname,errorlint,forbidigo -D=staticcheck --timeout=30m0s] in [] ...
  Error: 451-483 lines are duplicate of `pkg/blob/controllerserver_test.go:484-516` (dupl)
  Error: 484-516 lines are duplicate of `pkg/blob/controllerserver_test.go:451-483` (dupl)
  Error: Error return value of `(k8s.io/client-go/kubernetes/typed/core/v1.SecretInterface).Create` is not checked (errcheck)
  Error: Error return value of `(k8s.io/client-go/kubernetes/typed/core/v1.SecretInterface).Create` is not checked (errcheck)
  Warning: context-as-argument: context.Context should be the first parameter of a function (revive)
  Warning: var-declaration: should drop = nil from declaration of var expectedErr; it is the zero value (revive)
  Warning: var-declaration: should drop = nil from declaration of var expectedErr; it is the zero value (revive)
  Error: exporting a pointer for the loop variable test (exportloopref)
  Error: exporting a pointer for the loop variable test (exportloopref)
  Error: exporting a pointer for the loop variable test (exportloopref)
```

**Comment by aarongalang** [comment]
created a seperate pr for this issue, as I cant get rid of that first commit which lacks my userid. Will close this once the other(#736 ) is merged.

**Comment by andyzhangx** [comment]
`EasyCLA` is still not signed?

**Comment by aarongalang** [comment]
its on the other pr #736

**Comment by aarongalang** [comment]
first commit didnt use my user id, so I had to create a different branch with the changes

**Pull request closed without merging**
