### PR TITLE
test: enable windows unit tests

### LINKED ISSUE #253: test: Add support for running unit tests on Windows
**Describe the solution you'd like in detail**
Fix unit tests failures on Windows and add support for running unit tests on Windows on Github actions

**Additional context**

Similar - https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/406 , https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/556

### PR DESCRIPTION
**Pull request by mayankshah1607**
Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>

**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
enable windows unit tests
**Which issue(s) this PR fixes**:

Fixes #253

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
could you also enable `MacOS build & Unit Test`? thanks.

**Comment by mayankshah1607** [comment]
@andyzhangx Sure! Shall I add them in a other PR? Wanted to keep this one small and limited to Windows :)
Thanks

**Comment by andyzhangx** [comment]
> @andyzhangx Sure! Shall I add them in a other PR? Wanted to keep this one small and limited to Windows :)
> Thanks

yes

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
