### PR TITLE
feat: Add kubelet path parameter in helm chart installation

### LINKED ISSUE #309: add kubelet path parameter in helm chart installation
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

could refer to https://github.com/kubernetes-csi/csi-driver-smb/blob/a9a2e47b1790b18e722e9d0b4d413c4e8a520507/charts/latest/csi-driver-smb/values.yaml#L47-L49

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by dr0pdb**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
This PR adds the Kubelet path parameter in Helm chart installation.

**Which issue(s) this PR fixes**:

Fixes #309 

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:
none

**Release note**:
```
feat: Add kubelet path parameter in helm chart installation
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
/ok-to-test
would you also update the helm chart doc: https://github.com/kubernetes-sigs/blob-csi-driver/tree/master/charts

**Comment by dr0pdb** [comment]
@andyzhangx Updated the docs

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve
could you also port this feature to azure file driver? thanks.

**Comment by dr0pdb** [comment]
sure

**Pull request merged**
